using AcknowledgementShippingNotificationWatcher.Domain.ShippingNotificationConverters.Results;

namespace AsnMonitor.Application.Tests.AuditServices;

public class UnknownShippingNotificationConvertResult : IAcknowledgementShippingNotificationConvertResult
{
}