using AcknowledgementShippingNotificationWatcher.Domain.ShippingNotificationConverters.Results;

namespace AcknowledgementShippingNotificationWatcher.Tests.AuditServices;

public class UnknownShippingNotificationConvertResult : IAcknowledgementShippingNotificationConvertResult
{
}