// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AsnMonitor.AuditDb;

#nullable disable

namespace AsnMonitor.AuditDb.Migrations
{
    [DbContext(typeof(AsnAuditContext))]
    [Migration("20250416211131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AsnMonitor.AuditDb.Models.Box", b =>
                {
                    b.Property<string>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BoxId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("AsnMonitor.AuditDb.Models.ProductLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.ToTable("ProductLine");
                });

            modelBuilder.Entity("AsnMonitor.AuditDb.Models.ProductLine", b =>
                {
                    b.HasOne("AsnMonitor.AuditDb.Models.Box", null)
                        .WithMany("Products")
                        .HasForeignKey("BoxId");
                });

            modelBuilder.Entity("AsnMonitor.AuditDb.Models.Box", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
