using AcknowledgementShippingNotificationWatcher.Domain.NotificationInputs;
using AcknowledgementShippingNotificationWatcher.Domain.ShippingNotificationConverters.Results;

namespace AcknowledgementShippingNotificationWatcher.Domain.ShippingNotificationConverters;

public interface IAcknowledgementShippingNotificationConverter
{
    IAcknowledgementShippingNotificationConvertResult Convert(AcknowledgementShippingNotificationInput input);
    
}